# Generated by Django 4.2.5 on 2023-09-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devengados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccionar', models.BooleanField(default=False)),
                ('enviado', models.BooleanField(default=False)),
                ('emision', models.CharField(blank=True, max_length=10, null=True)),
                ('alta', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('nroFactura', models.CharField(blank=True, max_length=30)),
                ('proveedor', models.CharField(blank=True, max_length=70)),
                ('oc', models.CharField(blank=True, max_length=30)),
                ('importe', models.FloatField(blank=True)),
                ('ff', models.CharField(blank=True, max_length=10)),
                ('unidadEjecutora', models.CharField(blank=True, max_length=10)),
                ('objeto', models.TextField(blank=True)),
                ('fondoAfectado', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'devengados',
            },
        ),
    ]
