# Generated by Django 4.2.5 on 2023-09-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadroprincipal',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroprincipal',
            name='factura',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroprincipal',
            name='ff',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroprincipal',
            name='nroFactura',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroprincipal',
            name='objeto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroprincipal',
            name='oc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroprincipal',
            name='proveedor',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroprincipal',
            name='unidadEjecutora',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
