# Generated by Django 4.2.5 on 2023-09-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_cuadroprincipal_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadroprincipal',
            name='alta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cuadroprincipal',
            name='emision',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cuadroprincipal',
            name='fondoAfectado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
