# Generated by Django 4.2.5 on 2023-09-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_devengados_alta_alter_devengados_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devengados',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devengados',
            name='ff',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='devengados',
            name='importe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devengados',
            name='nroFactura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devengados',
            name='objeto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devengados',
            name='oc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devengados',
            name='proveedor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devengados',
            name='unidadEjecutora',
            field=models.TextField(blank=True, null=True),
        ),
    ]
