# Generated by Django 4.2.5 on 2023-09-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_cuadroprincipal_alta_cuadroprincipal_emision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadroprincipal',
            name='objeto',
        ),
    ]
