# Generated by Django 4.2.5 on 2023-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_remove_cuadroprincipal_objeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadroprincipal',
            name='objeto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
