# Generated by Django 4.2.5 on 2023-09-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_cuadroprincipal_enviado_cuadroprincipal_selccionar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadroprincipal',
            name='enviado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cuadroprincipal',
            name='selccionar',
            field=models.BooleanField(),
        ),
    ]
