# Generated by Django 4.2.5 on 2023-09-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_alter_cuadroprincipal_enviado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadroprincipal',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuadroprincipal',
            name='selccionar',
            field=models.BooleanField(default=False),
        ),
    ]
